### ISSUE TITLE
Not posting photos [Bug] 

### ISSUE THREAD

**Issue by Mykietry** [Josee9988/Daily-image-discord-bot#20] opened 2021-06-14 17:20 UTC
# **🐞 Bug Report**

## **Describe the bug**

* Hi! I'm setting up the bot everything is working as in it's responding when i've been doing the set up commands however, despite responding when I complete the channel command it won't actually post a picture, when i attempt the now command its either ignored or says that i need to type the command in the previously chosen channel
* 
---

### **Is this a regression?**

---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

*

---

### **Media prove**

---

### **Your environment**

* OS: 
* Node version:
* Npm version:
* Browser name and version:

---

### **Additional context**

*

**Comment by Josee9988** [comment] 2021-06-14 17:25
May you send an email with your serverID to jgracia9988@gmail.com?

Do you have a voice channel with the same name as the one you set up?

Thanks

**Comment by Mykietry** [comment] 2021-06-14 17:35
Sent and i did but i had changed it and tried again with the same results

**Comment by Josee9988** [comment] 2021-06-14 17:39
Seems like you are using a google drive link for the "album link" and not a google photos album link. The setting albumlink must receive valid google photos public album

eg: "https://photos.google.com/share/..."
or "https://photos.app.goo.gl/..."

Try that first!

**Comment by Mykietry** [comment] 2021-06-14 17:45
okay thank you! I knew it would be something on my end!

**Comment by Josee9988** [comment] 2021-06-14 17:50
Just check it and let me know if the problem persists.

Thanks for your time!

**Comment by Mykietry** [comment] 2021-06-14 17:53
It's working in my test channel but when i then change the channel to be for my channel called general it sends this instead of the photo :interrobang:To use this command, talk in the previously selected channel

**Comment by Josee9988** [comment] 2021-06-14 17:57
Maybe you have a general voice chat channel as well? I do not know your server structure and I am maybe missing some information that could help solving this problem

**Comment by Mykietry** [comment] 2021-06-14 18:04
It's genuinely only working on the private channel i made to test it but not on any of my public channels. I've made sure to make sure no vc have the same name and that no other channel has the words general in it

**Comment by Josee9988** [comment] 2021-06-14 18:07
If you could export the server structure as a template or just add me temporarily to your server I could check this out, but this will have to wait a couple of days as I am a bit busy rn.

Sorry for the inconveniences ;(

**Comment by Mykietry** [comment] 2021-06-14 18:13
I dont know how to export the server structure, i'll see if i can figure it out

Im not the maker of the server just have admin rights and the original creator doesn't wish for me to add you, sorry! 

Don't worry I'll see if there's anything I can figure out on my end! thanks for helping me so far!

**Comment by Josee9988** [comment] 2021-06-14 18:17
I think discord has a template feature so you can export it and then create a new server from such a template.

I really can not do much from here if I don't deeply analyze what might be going on in your case. I haven't been warned about this issue so I really do not know what might be causing it.

Anyways, I'll try to refactor the code and check for possible malfunctions soon.

Thanks and sorry for the issue ❤️

**Comment by Mykietry** [comment] 2021-06-14 18:26
https://discord.new/CUnqDQgRr8Ev is it this?

**Comment by Josee9988** [comment] 2021-06-14 18:49
I think so, please tell me the channel name that you wanted the pictures to appear in

**Comment by Mykietry** [comment] 2021-06-14 18:59
general under home room

**Comment by Josee9988** [comment] 2021-06-21 13:30
I'm actually trying to solve your issue

**Comment by Josee9988** [comment] 2021-06-21 13:58
Hi @Mykietry this should be fixed now :) Please try it out.

Thanks for your time!

**Comment by Mykietry** [comment] 2021-06-21 16:19
It worked! Thank you very much!
I've noticed however that it hasn't been posting a picture every 12 hours, is that something I've done on my end?

**Comment by Josee9988** [comment] 2021-06-21 18:54
The bot has been restarted a couple of times today to apply the new version, the Cron scheduler might have been reinitialised so, it should post new pictures tomorrow or in a couple of hours! If not please open an issue or just comment again @Mykietry ;)

**Comment by Josee9988** [comment] 2021-06-22 06:40
@Mykietry has It posted a photo?

**Comment by Mykietry** [comment] 2021-06-22 07:51
No, nothing so far

**Comment by Josee9988** [comment] 2021-06-22 10:12
Well that's weird, I will check it later!

**Comment by Josee9988** [comment] 2021-06-22 10:12
Does it work if you do !dimg now ?

**Comment by Mykietry** [comment] 2021-06-22 10:22
Yeah the now command works it's just the 12hr ones that don't post

**Comment by Josee9988** [comment] 2021-06-22 11:15
Okey I'll work on it!

**Comment by Josee9988** [comment] 2021-06-22 11:20
Are you still working in your general channel, right? As I'm testing the bot out with your server template and I wanted to make sure I was using the same server as yours

**Comment by Josee9988** [comment] 2021-06-23 11:56
Hi @Mykietry , I've been testing and seems like the problem is caused by a third party server that had a broken album link and stopped the corn job.

Please try to re-set the channel using `!dimg channel nameOfTheChannel`
Or kick and re-invite the bot

This should fix the problem, please tell me if that does fix it for you 
:) Thanks

**Comment by Mykietry** [comment] 2021-06-23 12:38
Okay thank you, I'll try what you recommend and let you know

**Comment by Josee9988** [comment] 2021-06-25 05:40
Seems like there is already a problem. I'll fix it in the upcoming days

**Comment by Josee9988** [comment] 2021-06-27 13:09
@Mykietry does it work for you now?

**Comment by Mykietry** [comment] 2021-06-27 13:12
Yes it's working now thank you so much!

**Comment by Josee9988** [comment] 2021-06-27 14:03
Thanks for your patience!

**Closed by Josee9988** 2021-06-27 14:03 UTC
Labels: Status: WIP, Type: Bug
